# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ec0518daec95b0ed2eed060034190285b8de5344076a9ef4161e5d8bece9ca18cf886b6c5e1b414ac00833fade3c6374eb8143154dc64a79fa5772ec345ea8af

test:
  secret_key_base: 90a9eee886c951e488814f2339d3f0ed65b0522141021a399f2bb63d87781e1e81781e6eea84c8528dabf16cf3ec7141536cdd31354f227c55f81b1b79d7f65b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
